$outputPath = "C:\Resume_App_app\Resume_App_app\testcases_resume_builder_500.xlsx"

$excel = New-Object -ComObject Excel.Application
$excel.Visible = $false
$excel.DisplayAlerts = $false

$workbook = $excel.Workbooks.Add()
$sheet = $workbook.Worksheets.Item(1)
$sheet.Name = "Test Cases"

# --- Headers ---
$headers = @("Test Case ID","Test Type","Feature/Section","Test Scenario","Test Steps","Test Data","Expected Result","Pass/Fail/Negative/Positive")
for ($c = 1; $c -le $headers.Count; $c++) {
    $sheet.Cells.Item(1, $c) = $headers[$c-1]
    $sheet.Cells.Item(1, $c).Font.Bold = $true
    $sheet.Cells.Item(1, $c).Interior.ColorIndex = 37
    $sheet.Cells.Item(1, $c).Font.Color = [System.Drawing.ColorTranslator]::ToOle([System.Drawing.Color]::White)
}

# --- Data rows ---
$rows = @(
# UNIT TESTS - Save & Exit
@("TC_001","Unit","Save & Exit","Verify button renders","Open Resume Builder, check for Save & Exit button","","Button is visible","Positive"),
@("TC_002","Unit","Save & Exit","Verify button is clickable","Click Save & Exit button","","App saves and exits","Positive"),
@("TC_003","Unit","Save & Exit","Verify save with empty data","Click Save & Exit with no data filled","Empty","Warning shown or saves empty","Negative"),
@("TC_004","Unit","Save & Exit","Verify save with partial data","Fill 3 sections and click Save & Exit","Partial data","Progress saved","Positive"),
@("TC_005","Unit","Save & Exit","Verify save with full data","Fill all sections and click Save & Exit","Full data","All data saved","Positive"),
@("TC_006","Unit","Save & Exit","Verify save with special characters","Fill fields with special chars, click Save & Exit","!@#$%^&*","Data saved with special chars","Positive"),
@("TC_007","Unit","Save & Exit","Verify save with long text","Fill fields with 1000+ characters, click Save & Exit","Long text","Data saved or truncated","Positive"),
@("TC_008","Unit","Save & Exit","Verify save with numbers only","Fill name field with numbers, click Save & Exit","12345","Data saved","Positive"),
@("TC_009","Unit","Save & Exit","Verify save with emoji","Fill fields with emoji, click Save & Exit","😊🎓","Data saved","Positive"),
@("TC_010","Unit","Save & Exit","Verify save with whitespace","Fill fields with spaces only, click Save & Exit","   ","Warning or trimmed","Negative"),
# UNIT TESTS - Preview & Export
@("TC_011","Unit","Preview & Export","Verify button renders","Open Resume Builder, check for Preview & Export button","","Button is visible","Positive"),
@("TC_012","Unit","Preview & Export","Verify export with all sections complete","Complete all sections, click Preview & Export","Full data","PDF generated","Positive"),
@("TC_013","Unit","Preview & Export","Verify export with incomplete sections","Leave some sections incomplete, click Preview & Export","Partial data","Warning shown","Negative"),
@("TC_014","Unit","Preview & Export","Verify export with Modern template","Select Modern template, click Preview & Export","Modern","PDF with Modern template","Positive"),
@("TC_015","Unit","Preview & Export","Verify export with Classic template","Select Classic template, click Preview & Export","Classic","PDF with Classic template","Positive"),
@("TC_016","Unit","Preview & Export","Verify export with Creative template","Select Creative template, click Preview & Export","Creative","PDF with Creative template","Positive"),
@("TC_017","Unit","Preview & Export","Verify export in English","Select English language, click Preview & Export","English","PDF in English","Positive"),
@("TC_018","Unit","Preview & Export","Verify export in French","Select French language, click Preview & Export","French","PDF in French","Positive"),
@("TC_019","Unit","Preview & Export","Verify export in Spanish","Select Spanish language, click Preview & Export","Spanish","PDF in Spanish","Positive"),
@("TC_020","Unit","Preview & Export","Verify export with empty sections","Leave all sections empty, click Preview & Export","Empty","Warning shown","Negative"),
@("TC_021","Unit","Preview & Export","Verify export with special characters","Fill sections with special chars, export","!@#$%^&*","PDF generated","Positive"),
@("TC_022","Unit","Preview & Export","Verify export file format","Click Preview & Export, check file format","","File is PDF","Positive"),
@("TC_023","Unit","Preview & Export","Verify export file name","Click Preview & Export, check file name","","File name matches resume name","Positive"),
@("TC_024","Unit","Preview & Export","Verify export file size","Export a full resume, check file size","Full data","File size within limits","Positive"),
@("TC_025","Unit","Preview & Export","Verify export with large data","Max data in all sections, export","Max data","PDF generated","Positive"),
@("TC_026","Unit","Preview & Export","Verify export with duplicate data","Duplicate entries in sections, export","Duplicate","PDF generated","Positive"),
@("TC_027","Unit","Preview & Export","Verify export with invalid data","Invalid data in sections, export","Invalid data","Error or warning shown","Negative"),
@("TC_028","Unit","Preview & Export","Verify export with missing required fields","Leave required fields empty, export","Missing fields","Warning shown","Negative"),
@("TC_029","Unit","Preview & Export","Verify export with reordered sections","Reorder sections, export","Reordered","PDF with new order","Positive"),
@("TC_030","Unit","Preview & Export","Verify export with all templates","Switch templates and export each","All templates","PDFs generated for each","Positive"),
# UNIT TESTS - Progress Bar
@("TC_031","Unit","Progress Bar","Verify initial progress","Open Resume Builder, check progress bar","0","Shows 0%","Positive"),
@("TC_032","Unit","Progress Bar","Verify progress after 1 section","Complete 1 section, check progress","1/8","Shows 12.5%","Positive"),
@("TC_033","Unit","Progress Bar","Verify progress after 2 sections","Complete 2 sections, check progress","2/8","Shows 25%","Positive"),
@("TC_034","Unit","Progress Bar","Verify progress after 3 sections","Complete 3 sections, check progress","3/8","Shows 37.5%","Positive"),
@("TC_035","Unit","Progress Bar","Verify progress after 4 sections","Complete 4 sections, check progress","4/8","Shows 50%","Positive"),
@("TC_036","Unit","Progress Bar","Verify progress after 5 sections","Complete 5 sections, check progress","5/8","Shows 62.5%","Positive"),
@("TC_037","Unit","Progress Bar","Verify progress after 6 sections","Complete 6 sections, check progress","6/8","Shows 75%","Positive"),
@("TC_038","Unit","Progress Bar","Verify progress after 7 sections","Complete 7 sections, check progress","7/8","Shows 87.5%","Positive"),
@("TC_039","Unit","Progress Bar","Verify progress after all sections","Complete all 8 sections, check progress","8/8","Shows 100%","Positive"),
@("TC_040","Unit","Progress Bar","Verify progress overflow","Set progress > 100%","110%","Shows max 100%","Negative"),
@("TC_041","Unit","Progress Bar","Verify progress underflow","Set progress < 0%","-10%","Shows min 0%","Negative"),
@("TC_042","Unit","Progress Bar","Verify progress decreases on delete","Complete a section, then delete entry, check progress","","Progress decreases","Positive"),
@("TC_043","Unit","Progress Bar","Verify progress color","Check progress bar color at 0%","0%","Shows default color","Positive"),
@("TC_044","Unit","Progress Bar","Verify progress color","Check progress bar color at 100%","100%","Shows completed color","Positive"),
@("TC_045","Unit","Progress Bar","Verify progress animation","Complete a section, check animation","","Animation plays","Positive"),
# UNIT TESTS - Resume Template
@("TC_046","Unit","Resume Template","Verify template card renders","Open Resume Builder, check template card","","Card is visible","Positive"),
@("TC_047","Unit","Resume Template","Verify default template","Open Resume Builder, note default template","","Default template shown","Positive"),
@("TC_048","Unit","Resume Template","Verify change to Modern","Click Change, select Modern","Modern","Template updates to Modern","Positive"),
@("TC_049","Unit","Resume Template","Verify change to Classic","Click Change, select Classic","Classic","Template updates to Classic","Positive"),
@("TC_050","Unit","Resume Template","Verify change to Creative","Click Change, select Creative","Creative","Template updates to Creative","Positive"),
@("TC_051","Unit","Resume Template","Verify change to Minimal","Click Change, select Minimal","Minimal","Template updates to Minimal","Positive"),
@("TC_052","Unit","Resume Template","Verify change to Professional","Click Change, select Professional","Professional","Template updates to Professional","Positive"),
@("TC_053","Unit","Resume Template","Verify template persists on save","Change template, save, reopen","Classic","Template persists","Positive"),
@("TC_054","Unit","Resume Template","Verify template in export","Change template, export","Classic","PDF uses selected template","Positive"),
@("TC_055","Unit","Resume Template","Verify invalid template","Select invalid template","Invalid","Error shown","Negative"),
@("TC_056","Unit","Resume Template","Verify template preview","Click Change, hover over template","Modern","Preview shown","Positive"),
@("TC_057","Unit","Resume Template","Verify cancel template change","Click Change, then Cancel","","Template unchanged","Positive"),
@("TC_058","Unit","Resume Template","Verify template modal closes on select","Select template from modal","Classic","Modal closes","Positive"),
@("TC_059","Unit","Resume Template","Verify all templates available","Open template modal, count templates","","All templates listed","Positive"),
@("TC_060","Unit","Resume Template","Verify template thumbnail","Open template modal, check thumbnails","","Thumbnails visible","Positive"),
# UNIT TESTS - Resume Language
@("TC_061","Unit","Resume Language","Verify language card renders","Open Resume Builder, check language card","","Card is visible","Positive"),
@("TC_062","Unit","Resume Language","Verify default language","Open Resume Builder, note default language","","Default language shown","Positive"),
@("TC_063","Unit","Resume Language","Verify change to English","Click Change, select English","English","Language updates to English","Positive"),
@("TC_064","Unit","Resume Language","Verify change to French","Click Change, select French","French","Language updates to French","Positive"),
@("TC_065","Unit","Resume Language","Verify change to Spanish","Click Change, select Spanish","Spanish","Language updates to Spanish","Positive"),
@("TC_066","Unit","Resume Language","Verify change to German","Click Change, select German","German","Language updates to German","Positive"),
@("TC_067","Unit","Resume Language","Verify change to Arabic","Click Change, select Arabic","Arabic","Language updates to Arabic","Positive"),
@("TC_068","Unit","Resume Language","Verify language persists on save","Change language, save, reopen","French","Language persists","Positive"),
@("TC_069","Unit","Resume Language","Verify language in export","Change language, export","French","PDF in selected language","Positive"),
@("TC_070","Unit","Resume Language","Verify invalid language","Select invalid language","Invalid","Error shown","Negative"),
@("TC_071","Unit","Resume Language","Verify cancel language change","Click Change, then Cancel","","Language unchanged","Positive"),
@("TC_072","Unit","Resume Language","Verify language modal closes on select","Select language from modal","French","Modal closes","Positive"),
@("TC_073","Unit","Resume Language","Verify all languages available","Open language modal, count languages","","All languages listed","Positive"),
# UNIT TESTS - Sections
@("TC_074","Unit","Personal Information","Verify section card renders","Open Resume Builder","","Card is visible","Positive"),
@("TC_075","Unit","Personal Information","Verify required fields","Open Personal Information editor","","Required fields marked","Positive"),
@("TC_076","Unit","Personal Information","Verify full name field","Enter full name","John Doe","Name saved","Positive"),
@("TC_077","Unit","Personal Information","Verify email field","Enter email","john@email.com","Email saved","Positive"),
@("TC_078","Unit","Personal Information","Verify invalid email","Enter invalid email","not-an-email","Error shown","Negative"),
@("TC_079","Unit","Personal Information","Verify phone field","Enter phone number","+1234567890","Phone saved","Positive"),
@("TC_080","Unit","Personal Information","Verify invalid phone","Enter invalid phone","abc","Error shown","Negative"),
@("TC_081","Unit","Personal Information","Verify address field","Enter address","123 Main St","Address saved","Positive"),
@("TC_082","Unit","Personal Information","Verify profile photo upload","Upload a photo","JPEG file","Photo saved","Positive"),
@("TC_083","Unit","Personal Information","Verify invalid photo format","Upload non-image file","PDF file","Error shown","Negative"),
@("TC_084","Unit","Personal Information","Verify empty required fields","Leave required fields empty","","Error shown","Negative"),
@("TC_085","Unit","Personal Information","Verify long name","Enter 200+ char name","Long name","Error or truncation","Negative"),
@("TC_086","Unit","Personal Information","Verify special chars in name","Enter special chars in name","!@#$%","Error shown","Negative"),
@("TC_087","Unit","Professional Summary","Verify section card renders","Open Resume Builder","","Card is visible","Positive"),
@("TC_088","Unit","Professional Summary","Verify text field","Enter summary text","Summary text","Text saved","Positive"),
@("TC_089","Unit","Professional Summary","Verify max characters","Enter 500+ characters","Long text","Text saved or truncated","Positive"),
@("TC_090","Unit","Professional Summary","Verify empty field","Leave summary empty","","Warning shown","Negative"),
@("TC_091","Unit","Professional Summary","Verify special chars","Enter special chars in summary","!@#$%^","Text saved","Positive"),
@("TC_092","Unit","Work Experience","Verify section card renders","Open Resume Builder","","Card is visible","Positive"),
@("TC_093","Unit","Work Experience","Verify add new entry","Click Add, enter details","Job title, company","Entry saved","Positive"),
@("TC_094","Unit","Work Experience","Verify edit entry","Edit existing entry","Updated job title","Entry updated","Positive"),
@("TC_095","Unit","Work Experience","Verify delete entry","Delete an entry","","Entry removed","Positive"),
@("TC_096","Unit","Work Experience","Verify start date field","Enter start date","01/2020","Date saved","Positive"),
@("TC_097","Unit","Work Experience","Verify end date field","Enter end date","12/2023","Date saved","Positive"),
@("TC_098","Unit","Work Experience","Verify end date before start date","Set end date before start date","Invalid dates","Error shown","Negative"),
@("TC_099","Unit","Work Experience","Verify current job checkbox","Check 'Currently working here'","","End date disabled","Positive"),
@("TC_100","Unit","Work Experience","Verify multiple entries","Add 5 work experience entries","5 entries","All entries saved","Positive"),
@("TC_101","Unit","Education","Verify section card renders","Open Resume Builder","","Card is visible","Positive"),
@("TC_102","Unit","Education","Verify add new entry","Click Add, enter details","Degree, institution","Entry saved","Positive"),
@("TC_103","Unit","Education","Verify edit entry","Edit existing entry","Updated degree","Entry updated","Positive"),
@("TC_104","Unit","Education","Verify delete entry","Delete an entry","","Entry removed","Positive"),
@("TC_105","Unit","Education","Verify multiple entries","Add 3 education entries","3 entries","All entries saved","Positive"),
@("TC_106","Unit","Education","Verify invalid year","Enter invalid graduation year","abcd","Error shown","Negative"),
@("TC_107","Unit","Skills","Verify section card renders","Open Resume Builder","","Card is visible","Positive"),
@("TC_108","Unit","Skills","Verify add skill","Enter a skill","Flutter","Skill saved","Positive"),
@("TC_109","Unit","Skills","Verify add multiple skills","Enter 10 skills","10 skills","All skills saved","Positive"),
@("TC_110","Unit","Skills","Verify delete skill","Delete a skill","","Skill removed","Positive"),
@("TC_111","Unit","Skills","Verify skill level","Set skill proficiency level","Beginner/Intermediate/Expert","Level saved","Positive"),
@("TC_112","Unit","Skills","Verify empty skill","Submit empty skill field","","Error shown","Negative"),
@("TC_113","Unit","Skills","Verify duplicate skill","Add same skill twice","Duplicate","Warning shown","Negative"),
@("TC_114","Unit","Projects","Verify section card renders","Open Resume Builder","","Card is visible","Positive"),
@("TC_115","Unit","Projects","Verify add project","Enter project details","Project name, description","Entry saved","Positive"),
@("TC_116","Unit","Projects","Verify edit project","Edit existing project","Updated name","Entry updated","Positive"),
@("TC_117","Unit","Projects","Verify delete project","Delete a project","","Entry removed","Positive"),
@("TC_118","Unit","Projects","Verify project link","Enter project URL","https://github.com","Link saved","Positive"),
@("TC_119","Unit","Projects","Verify invalid project link","Enter invalid URL","not-a-url","Error shown","Negative"),
@("TC_120","Unit","Certifications","Verify section card renders","Open Resume Builder","","Card is visible","Positive"),
@("TC_121","Unit","Certifications","Verify add certification","Enter certification details","AWS Certified","Entry saved","Positive"),
@("TC_122","Unit","Certifications","Verify edit certification","Edit existing certification","Updated name","Entry updated","Positive"),
@("TC_123","Unit","Certifications","Verify delete certification","Delete a certification","","Entry removed","Positive"),
@("TC_124","Unit","Certifications","Verify expiry date","Enter expiry date","12/2025","Date saved","Positive"),
@("TC_125","Unit","Certifications","Verify past expiry date","Enter past expiry date","01/2020","Warning shown","Negative"),
@("TC_126","Unit","Languages","Verify section card renders","Open Resume Builder","","Card is visible","Positive"),
@("TC_127","Unit","Languages","Verify add language","Enter language","French","Language saved","Positive"),
@("TC_128","Unit","Languages","Verify language proficiency","Set proficiency level","Native/Fluent/Basic","Level saved","Positive"),
@("TC_129","Unit","Languages","Verify delete language","Delete a language","","Language removed","Positive"),
@("TC_130","Unit","Languages","Verify duplicate language","Add same language twice","Duplicate","Warning shown","Negative"),
# INTEGRATION TESTS
@("TC_131","Integration","Progress & Sections","Progress updates when section completed","Complete Personal Info, check progress bar","Full personal info","Progress increases to 12.5%","Positive"),
@("TC_132","Integration","Progress & Sections","Progress updates when section cleared","Clear all Personal Info fields, check progress","","Progress decreases","Positive"),
@("TC_133","Integration","Template & Export","Export reflects selected template","Select Classic, export","Classic","PDF uses Classic template","Positive"),
@("TC_134","Integration","Language & Export","Export reflects selected language","Select French, export","French","PDF in French","Positive"),
@("TC_135","Integration","Sections & Export","Export includes all section data","Fill all sections, export","Full data","All data in PDF","Positive"),
@("TC_136","Integration","Save & Reload","Saved data reloads correctly","Fill sections, save, close, reopen","Saved data","All data reloaded","Positive"),
@("TC_137","Integration","Template & Preview","Preview updates on template change","Change template, check preview","Classic","Preview updates","Positive"),
@("TC_138","Integration","Language & Sections","Section labels update on language change","Change language, check section labels","French","Labels in French","Positive"),
@("TC_139","Integration","Skills & Export","Skills appear in exported PDF","Add skills, export","Flutter, Dart","Skills in PDF","Positive"),
@("TC_140","Integration","Work Experience & Export","Work experience in PDF","Add work exp, export","Job details","Work exp in PDF","Positive"),
@("TC_141","Integration","Education & Export","Education in PDF","Add education, export","Degree details","Education in PDF","Positive"),
@("TC_142","Integration","Projects & Export","Projects in PDF","Add projects, export","Project details","Projects in PDF","Positive"),
@("TC_143","Integration","Certifications & Export","Certifications in PDF","Add certifications, export","Cert details","Certs in PDF","Positive"),
@("TC_144","Integration","Languages & Export","Languages in PDF","Add languages, export","French - Fluent","Languages in PDF","Positive"),
@("TC_145","Integration","Photo & Export","Photo appears in PDF","Upload photo, export","JPEG photo","Photo in PDF","Positive"),
@("TC_146","Integration","Multiple Templates","Switch templates and export each","Switch through all templates, export each","All templates","PDFs generated for each","Positive"),
@("TC_147","Integration","Multiple Languages","Switch languages and export each","Switch through all languages, export each","All languages","PDFs in each language","Positive"),
@("TC_148","Integration","Delete & Progress","Progress decreases on entry delete","Complete section, delete entry, check progress","","Progress decreases","Positive"),
@("TC_149","Integration","Add & Progress","Progress increases on entry add","Add entry to incomplete section, check progress","","Progress increases","Positive"),
@("TC_150","Integration","Save & Export","Export uses saved data","Fill sections, save, export","Saved data","PDF uses saved data","Positive"),
# SYSTEM TESTS
@("TC_151","System","Full Resume Creation","Create complete resume from scratch","Fill all sections with valid data, save, export","Full valid data","Resume created and exported","Positive"),
@("TC_152","System","Resume Persistence","Resume persists across app restarts","Fill sections, close app, reopen","Saved data","All data reloaded","Positive"),
@("TC_153","System","Multiple Resumes","Create and manage multiple resumes","Create 3 resumes, switch between them","3 resumes","Each resume has correct data","Positive"),
@("TC_154","System","Template Switch","Switch template without losing data","Change template, verify data intact","Classic template","Data unchanged","Positive"),
@("TC_155","System","Language Switch","Switch language without losing data","Change language, verify data intact","French","Data unchanged","Positive"),
@("TC_156","System","Export Multiple Formats","Export resume in all available formats","Export as PDF, DOCX, etc.","Full data","All formats generated","Positive"),
@("TC_157","System","Network Failure","App behaves on network failure","Disconnect network, try to save/export","No network","Graceful error shown","Negative"),
@("TC_158","System","Storage Full","App behaves when storage is full","Fill storage, try to save","Storage full","Graceful error shown","Negative"),
@("TC_159","System","App Update","Data persists after app update","Update app, check resume data","Saved data","Data intact","Positive"),
@("TC_160","System","Concurrent Edits","Edit same resume on two devices","Edit on device A and B simultaneously","Conflict","Conflict handled","Negative"),
@("TC_161","System","Large Resume","Create resume with max data in all sections","Max data in all fields","Max data","App remains responsive","Positive"),
@("TC_162","System","Resume Sharing","Share resume with others","Fill sections, share resume","Full data","Resume shared correctly","Positive"),
@("TC_163","System","Resume Deletion","Delete a resume","Create resume, delete it","","Resume removed","Positive"),
@("TC_164","System","Resume Restore","Restore deleted resume","Delete resume, restore from trash","","Resume restored","Positive"),
@("TC_165","System","Resume Duplication","Duplicate a resume","Create resume, duplicate it","","New copy created","Positive"),
@("TC_166","System","Offline Mode","App works offline","Disconnect, create resume, save","No network","Data saved locally","Positive"),
@("TC_167","System","Sync on Reconnect","Data syncs on reconnect","Create resume offline, reconnect","Offline data","Data synced","Positive"),
@("TC_168","System","Theme Change","UI updates on theme change","Change theme, check UI","Dark/Light","UI updates","Positive"),
@("TC_169","System","Font Change","UI updates on font change","Change font, check UI","Different font","UI updates","Positive"),
@("TC_170","System","Accessibility","Screen reader compatibility","Enable screen reader, navigate app","Screen reader","All elements accessible","Positive"),
# FUNCTIONAL TESTS
@("TC_171","Functional","Personal Info","User can add personal info","Fill all personal info fields, save","Valid data","Data saved","Positive"),
@("TC_172","Functional","Personal Info","User can edit personal info","Edit existing personal info, save","Updated data","Data updated","Positive"),
@("TC_173","Functional","Personal Info","User can delete personal info","Clear all personal info fields, save","","Fields cleared","Positive"),
@("TC_174","Functional","Work Experience","User can add work experience","Add work experience entry, save","Valid data","Entry saved","Positive"),
@("TC_175","Functional","Work Experience","User can edit work experience","Edit existing entry, save","Updated data","Entry updated","Positive"),
@("TC_176","Functional","Work Experience","User can delete work experience","Delete entry","","Entry removed","Positive"),
@("TC_177","Functional","Work Experience","User can add multiple entries","Add 5 entries","5 valid entries","All entries saved","Positive"),
@("TC_178","Functional","Education","User can add education","Add education entry, save","Valid data","Entry saved","Positive"),
@("TC_179","Functional","Education","User can edit education","Edit existing entry, save","Updated data","Entry updated","Positive"),
@("TC_180","Functional","Education","User can delete education","Delete entry","","Entry removed","Positive"),
@("TC_181","Functional","Skills","User can add skills","Add 10 skills","10 valid skills","All saved","Positive"),
@("TC_182","Functional","Skills","User can edit skills","Edit skill name/level","Updated skill","Skill updated","Positive"),
@("TC_183","Functional","Skills","User can delete skills","Delete a skill","","Skill removed","Positive"),
@("TC_184","Functional","Projects","User can add projects","Add project entry, save","Valid data","Entry saved","Positive"),
@("TC_185","Functional","Projects","User can edit projects","Edit existing project, save","Updated data","Entry updated","Positive"),
@("TC_186","Functional","Projects","User can delete projects","Delete project","","Entry removed","Positive"),
@("TC_187","Functional","Certifications","User can add certifications","Add certification, save","Valid data","Entry saved","Positive"),
@("TC_188","Functional","Certifications","User can edit certifications","Edit existing cert, save","Updated data","Entry updated","Positive"),
@("TC_189","Functional","Certifications","User can delete certifications","Delete cert","","Entry removed","Positive"),
@("TC_190","Functional","Languages","User can add languages","Add language, save","French - Fluent","Entry saved","Positive"),
@("TC_191","Functional","Languages","User can edit languages","Edit language/proficiency, save","Updated data","Entry updated","Positive"),
@("TC_192","Functional","Languages","User can delete languages","Delete language","","Entry removed","Positive"),
@("TC_193","Functional","Professional Summary","User can add summary","Enter summary text, save","Valid text","Text saved","Positive"),
@("TC_194","Functional","Professional Summary","User can edit summary","Edit existing summary, save","Updated text","Text updated","Positive"),
@("TC_195","Functional","Professional Summary","User can clear summary","Clear summary text, save","","Field cleared","Positive"),
@("TC_196","Functional","Template Selection","User can change template","Change template, verify change","Classic","Template updated","Positive"),
@("TC_197","Functional","Language Selection","User can change language","Change language, verify change","French","Language updated","Positive"),
@("TC_198","Functional","Export","User can export as PDF","Export resume as PDF","","PDF file generated","Positive"),
@("TC_199","Functional","Navigation","User can navigate to all sections","Click each section card","","Navigates to each section","Positive"),
@("TC_200","Functional","Navigation","Back button returns to main screen","Navigate to section, press Back","","Returns to main screen","Positive"),
# REGRESSION TESTS
@("TC_201","Regression","Save & Exit","Save still works after UI update","Update UI, test Save & Exit","Full data","Data saved","Positive"),
@("TC_202","Regression","Preview & Export","Export still works after template update","Update templates, test export","Modern","PDF generated","Positive"),
@("TC_203","Regression","Progress Bar","Progress bar still updates after logic change","Change progress logic, test","Full sections","Shows 100%","Positive"),
@("TC_204","Regression","Personal Info","Personal info still saves after schema change","Change schema, test save","Valid data","Data saved","Positive"),
@("TC_205","Regression","Work Experience","Work exp still saves after field addition","Add new field, test save","Valid data","Data saved","Positive"),
@("TC_206","Regression","Education","Education still saves after field removal","Remove field, test save","Valid data","Data saved","Positive"),
@("TC_207","Regression","Skills","Skills still work after level update","Update skill levels, test","10 skills","All saved","Positive"),
@("TC_208","Regression","Projects","Projects still work after link validation","Add link validation, test","Valid URL","Entry saved","Positive"),
@("TC_209","Regression","Certifications","Certs still work after date validation","Add date validation, test","Valid date","Entry saved","Positive"),
@("TC_210","Regression","Languages","Languages still work after proficiency change","Update proficiency levels, test","French - Fluent","Entry saved","Positive"),
@("TC_211","Regression","Navigation","Navigation still works after route change","Update routes, test navigation","","Navigates correctly","Positive"),
@("TC_212","Regression","Template","All templates still load after update","Update templates, check all load","All templates","All templates visible","Positive"),
@("TC_213","Regression","Language","All languages still load after update","Update language list, check all load","All languages","All languages visible","Positive"),
@("TC_214","Regression","Export","Export with all previous templates","Test export with old templates","All templates","PDFs generated","Positive"),
@("TC_215","Regression","Export","Export with all previous languages","Test export with old languages","All languages","PDFs generated","Positive"),
@("TC_216","Regression","Data Persistence","Old resumes load after update","Update app, load old resume","Old resume data","Data intact","Positive"),
@("TC_217","Regression","Progress Bar","Progress correct after section addition","Add new section, test progress","","Progress calculates correctly","Positive"),
@("TC_218","Regression","Progress Bar","Progress correct after section removal","Remove section, test progress","","Progress calculates correctly","Positive"),
@("TC_219","Regression","Photo Upload","Photo upload still works after update","Update upload logic, test photo upload","JPEG","Photo saved","Positive"),
@("TC_220","Regression","Sharing","Sharing still works after update","Update sharing, test share","Full data","Resume shared","Positive"),
# SMOKE TESTS
@("TC_221","Smoke","App Launch","App launches successfully","Open app","","App loads without errors","Positive"),
@("TC_222","Smoke","Resume Builder","Resume Builder opens","Navigate to Resume Builder","","Screen loads","Positive"),
@("TC_223","Smoke","Save & Exit","Save & Exit button works","Click Save & Exit","","App saves and exits","Positive"),
@("TC_224","Smoke","Preview & Export","Preview & Export button works","Click Preview & Export","","PDF generated","Positive"),
@("TC_225","Smoke","Section Navigation","All sections accessible","Click each section card","","All sections open","Positive"),
@("TC_226","Smoke","Template Change","Template can be changed","Click Change on template","Classic","Template updated","Positive"),
@("TC_227","Smoke","Language Change","Language can be changed","Click Change on language","French","Language updated","Positive"),
@("TC_228","Smoke","Progress Bar","Progress bar visible","Open Resume Builder","","Progress bar shown","Positive"),
@("TC_229","Smoke","Personal Info","Personal info can be entered","Fill personal info, save","Valid data","Data saved","Positive"),
@("TC_230","Smoke","Export","Resume can be exported","Complete sections, export","Full data","PDF generated","Positive"),
# SANITY TESTS
@("TC_231","Sanity","Save & Exit","Save works after bug fix","Apply bug fix, test Save & Exit","Full data","Data saved","Positive"),
@("TC_232","Sanity","Preview & Export","Export works after bug fix","Apply bug fix, test export","Full data","PDF generated","Positive"),
@("TC_233","Sanity","Personal Info","Personal info saves after fix","Apply fix, test save","Valid data","Data saved","Positive"),
@("TC_234","Sanity","Skills","Skills save after fix","Apply fix, test skills","10 skills","All saved","Positive"),
@("TC_235","Sanity","Progress Bar","Progress updates after fix","Apply fix, test progress","Full sections","Shows 100%","Positive"),
@("TC_236","Sanity","Navigation","Navigation works after fix","Apply fix, test navigation","","Navigates correctly","Positive"),
@("TC_237","Sanity","Template","Template change works after fix","Apply fix, test template change","Classic","Template updated","Positive"),
@("TC_238","Sanity","Language","Language change works after fix","Apply fix, test language change","French","Language updated","Positive"),
@("TC_239","Sanity","Export","Export works after fix","Apply fix, test export","Full data","PDF generated","Positive"),
@("TC_240","Sanity","Photo Upload","Photo upload works after fix","Apply fix, test upload","JPEG","Photo saved","Positive"),
# PERFORMANCE TESTS
@("TC_241","Performance","App Launch","App launches within 3 seconds","Open app, measure load time","","App loads < 3s","Positive"),
@("TC_242","Performance","Resume Builder","Screen loads within 2 seconds","Navigate to builder, measure time","","Loads < 2s","Positive"),
@("TC_243","Performance","Section Navigation","Section opens within 1 second","Click section, measure time","","Opens < 1s","Positive"),
@("TC_244","Performance","Export","Export completes within 5 seconds","Export full resume, measure time","Full data","Exports < 5s","Positive"),
@("TC_245","Performance","Save","Save completes within 2 seconds","Save resume, measure time","Full data","Saves < 2s","Positive"),
@("TC_246","Performance","Large Resume","App handles 20+ work experience entries","Add 20 entries, test performance","20 entries","App responsive","Positive"),
@("TC_247","Performance","Large Resume","App handles 20+ skills","Add 20 skills, test performance","20 skills","App responsive","Positive"),
@("TC_248","Performance","Large Resume","App handles 10+ projects","Add 10 projects, test performance","10 projects","App responsive","Positive"),
@("TC_249","Performance","Large Resume","Export large resume","Max data, export, measure time","Max data","Exports < 10s","Positive"),
@("TC_250","Performance","Scroll Performance","Scrolling is smooth","Scroll through all sections","","No lag","Positive"),
@("TC_251","Performance","Animation","Animations run at 60fps","Check animation frame rate","","60fps","Positive"),
@("TC_252","Performance","Memory","App memory usage is within limits","Monitor memory during use","","< 200MB","Positive"),
@("TC_253","Performance","CPU","CPU usage is within limits","Monitor CPU during use","","< 30% CPU","Positive"),
@("TC_254","Performance","Battery","Battery usage is within limits","Monitor battery during use","30 mins use","< 5% battery","Positive"),
@("TC_255","Performance","Network","API calls complete within 2 seconds","Test API calls, measure time","","< 2s","Positive"),
@("TC_256","Performance","Concurrent Users","App handles 100 concurrent users","Simulate 100 users","100 users","App responsive","Positive"),
@("TC_257","Performance","Stress Test","App handles 1000 rapid actions","Perform 1000 rapid taps","1000 actions","No crash","Positive"),
@("TC_258","Performance","Large PDF","Export PDF with high-res photo","Upload 5MB photo, export","5MB photo","PDF generated","Positive"),
@("TC_259","Performance","Database","Database queries within 500ms","Perform DB operations, measure","","< 500ms","Positive"),
@("TC_260","Performance","Load Test","App handles peak load","Simulate peak usage","Peak load","App responsive","Positive"),
# SECURITY TESTS
@("TC_261","Security","Input Validation","SQL injection in name field","Enter SQL in name","' OR 1=1 --","Input sanitized","Negative"),
@("TC_262","Security","Input Validation","SQL injection in email field","Enter SQL in email","' OR 1=1 --","Input sanitized","Negative"),
@("TC_263","Security","Input Validation","XSS in name field","Enter script in name","<script>alert(1)</script>","Input sanitized","Negative"),
@("TC_264","Security","Input Validation","XSS in summary field","Enter script in summary","<script>alert(1)</script>","Input sanitized","Negative"),
@("TC_265","Security","Input Validation","XSS in skill field","Enter script in skill","<script>alert(1)</script>","Input sanitized","Negative"),
@("TC_266","Security","Input Validation","HTML injection in name","Enter HTML in name","<h1>test</h1>","Input sanitized","Negative"),
@("TC_267","Security","Input Validation","HTML injection in summary","Enter HTML in summary","<b>bold</b>","Input sanitized","Negative"),
@("TC_268","Security","Access Control","Cannot access other user's resume","Try to access another user's resume URL","Another user's ID","Access denied","Negative"),
@("TC_269","Security","Access Control","Unauthorized export","Try to export without login","No auth token","Access denied","Negative"),
@("TC_270","Security","Access Control","Unauthorized edit","Try to edit without login","No auth token","Access denied","Negative"),
@("TC_271","Security","Data Encryption","Data encrypted at rest","Check stored data encryption","Saved data","Data encrypted","Positive"),
@("TC_272","Security","Data Encryption","Data encrypted in transit","Check network traffic","Network data","HTTPS used","Positive"),
@("TC_273","Security","Authentication","Session expires after inactivity","Leave app idle 30 mins","","Session expired","Positive"),
@("TC_274","Security","Authentication","Invalid token rejected","Use expired/invalid token","Invalid token","Access denied","Negative"),
@("TC_275","Security","File Upload","Malicious file upload","Upload executable as photo","EXE file","Upload rejected","Negative"),
@("TC_276","Security","File Upload","Oversized file rejected","Upload 50MB photo","50MB file","Upload rejected","Negative"),
@("TC_277","Security","File Upload","Valid file accepted","Upload 1MB JPEG","1MB JPEG","Upload accepted","Positive"),
@("TC_278","Security","Privacy","Resume data not leaked in logs","Check logs for PII","","No PII in logs","Positive"),
@("TC_279","Security","Privacy","Resume data not shared without consent","Check data sharing","","No unauthorized sharing","Positive"),
@("TC_280","Security","Brute Force","Multiple failed login attempts locked","Attempt 10 failed logins","10 wrong passwords","Account locked","Negative"),
@("TC_281","Security","CSRF","CSRF protection active","Attempt CSRF attack","CSRF token","Request rejected","Negative"),
@("TC_282","Security","Rate Limiting","Rate limiting on export","Export 100 times rapidly","100 requests","Rate limited","Negative"),
@("TC_283","Security","Secure Headers","HTTP security headers present","Check HTTP response headers","","Security headers present","Positive"),
@("TC_284","Security","Password","Password not stored in plain text","Check password storage","","Password hashed","Positive"),
@("TC_285","Security","Logout","Session cleared on logout","Login, logout, check session","","Session cleared","Positive"),
# USABILITY TESTS
@("TC_286","Usability","Navigation","All buttons clearly labeled","Review all buttons","","All buttons have labels","Positive"),
@("TC_287","Usability","Navigation","Navigation is intuitive","New user navigates without help","","User finds sections easily","Positive"),
@("TC_288","Usability","Navigation","Back button is accessible","Check back button placement","","Back button visible","Positive"),
@("TC_289","Usability","Navigation","Progress bar is understandable","Check progress bar UI","","Progress clearly shown","Positive"),
@("TC_290","Usability","Accessibility","Screen reader works","Enable screen reader, navigate","","All elements readable","Positive"),
@("TC_291","Usability","Accessibility","Font size adjustable","Increase font size, check UI","Large font","Text scales correctly","Positive"),
@("TC_292","Usability","Accessibility","Color contrast sufficient","Check color contrast ratio","","Contrast > 4.5:1","Positive"),
@("TC_293","Usability","Accessibility","Keyboard navigation works","Navigate app with keyboard","","All functions accessible","Positive"),
@("TC_294","Usability","Accessibility","Error messages are clear","Trigger validation errors","","Clear error messages","Positive"),
@("TC_295","Usability","Accessibility","Help text available","Check help text for fields","","Help text shown","Positive"),
@("TC_296","Usability","Mobile","UI adapts on mobile screen","Open on mobile device","","Layout adapts","Positive"),
@("TC_297","Usability","Mobile","Touch targets are large enough","Check button/tap target sizes","","Min 44x44px","Positive"),
@("TC_298","Usability","Mobile","Swipe gestures work","Swipe between sections","","Navigation works","Positive"),
@("TC_299","Usability","Desktop","UI adapts on desktop","Open on desktop","","Layout adapts","Positive"),
@("TC_300","Usability","Desktop","Mouse interaction works","Use mouse to navigate","","All clicks work","Positive"),
@("TC_301","Usability","Feedback","Success message on save","Save resume, check feedback","","Success message shown","Positive"),
@("TC_302","Usability","Feedback","Error message on failure","Trigger error, check feedback","","Error message shown","Positive"),
@("TC_303","Usability","Feedback","Loading indicator shown","Perform slow operation","","Loading spinner shown","Positive"),
@("TC_304","Usability","Feedback","Progress feedback on export","Export resume, check feedback","","Progress shown","Positive"),
@("TC_305","Usability","Onboarding","New user onboarding flow","New user opens app","","Onboarding shown","Positive"),
@("TC_306","Usability","Onboarding","Tips and hints visible","Check tips in UI","","Tips shown","Positive"),
@("TC_307","Usability","Onboarding","Tooltip on hover","Hover over icons","","Tooltips shown","Positive"),
@("TC_308","Usability","Consistency","UI consistent across screens","Check UI on all screens","","Consistent style","Positive"),
@("TC_309","Usability","Consistency","Icons consistent","Check icon styles","","Consistent icons","Positive"),
@("TC_310","Usability","Consistency","Typography consistent","Check font usage","","Consistent fonts","Positive"),
# NOTIFICATION TESTS
@("TC_311","Functional","Notifications","Verify initial state","Open Notifications screen","","Default states correct","Positive"),
@("TC_312","Functional","Notifications","Toggle Push Notifications ON","Tap Push Notifications toggle (OFF state)","OFF->ON","Toggle turns ON","Positive"),
@("TC_313","Functional","Notifications","Toggle Push Notifications OFF","Tap Push Notifications toggle (ON state)","ON->OFF","Toggle turns OFF","Positive"),
@("TC_314","Functional","Notifications","Toggle Email Notifications ON","Tap Email Notifications toggle","OFF->ON","Toggle turns ON","Positive"),
@("TC_315","Functional","Notifications","Toggle Email Notifications OFF","Tap Email Notifications toggle","ON->OFF","Toggle turns OFF","Positive"),
@("TC_316","Functional","Notifications","Toggle Resume Reminders ON","Tap Resume Reminders toggle","OFF->ON","Toggle turns ON","Positive"),
@("TC_317","Functional","Notifications","Toggle Resume Reminders OFF","Tap Resume Reminders toggle","ON->OFF","Toggle turns OFF","Positive"),
@("TC_318","Functional","Notifications","Toggle Job Alerts ON","Tap Job Alerts toggle","OFF->ON","Toggle turns ON","Positive"),
@("TC_319","Functional","Notifications","Toggle Job Alerts OFF","Tap Job Alerts toggle","ON->OFF","Toggle turns OFF","Positive"),
@("TC_320","Functional","Notifications","Toggle Subscription Alerts ON","Tap Subscription Alerts toggle","OFF->ON","Toggle turns ON","Positive"),
@("TC_321","Functional","Notifications","Toggle Subscription Alerts OFF","Tap Subscription Alerts toggle","ON->OFF","Toggle turns OFF","Positive"),
@("TC_322","Functional","Notifications","Toggle Tips & Updates ON","Tap Tips & Updates toggle","OFF->ON","Toggle turns ON","Positive"),
@("TC_323","Functional","Notifications","Toggle Tips & Updates OFF","Tap Tips & Updates toggle","ON->OFF","Toggle turns OFF","Positive"),
@("TC_324","Functional","Notifications","Push pref persists after restart","Toggle Push, restart app, check","","Preference persisted","Positive"),
@("TC_325","Functional","Notifications","Email pref persists after restart","Toggle Email, restart app, check","","Preference persisted","Positive"),
@("TC_326","Functional","Notifications","Reminder pref persists after restart","Toggle Reminders, restart app","","Preference persisted","Positive"),
@("TC_327","Functional","Notifications","Job Alerts pref persists","Toggle Job Alerts, restart app","","Preference persisted","Positive"),
@("TC_328","Functional","Notifications","Subscription pref persists","Toggle Subscription, restart app","","Preference persisted","Positive"),
@("TC_329","Functional","Notifications","Tips pref persists","Toggle Tips, restart app","","Preference persisted","Positive"),
@("TC_330","Functional","Notifications","All toggles OFF","Turn all toggles OFF","All OFF","No notifications","Positive"),
@("TC_331","Functional","Notifications","All toggles ON","Turn all toggles ON","All ON","All notifications active","Positive"),
@("TC_332","Functional","Notifications","Section headers visible","Open Notifications screen","","GENERAL/ACTIVITY/ACCOUNT visible","Positive"),
@("TC_333","Functional","Notifications","All subtitles visible","Open Notifications screen","","All subtitles correct","Positive"),
@("TC_334","Functional","Notifications","Back navigation works","Press back button","","Returns to previous screen","Positive"),
@("TC_335","Functional","Notifications","Rapid toggle changes","Toggle same switch multiple times rapidly","Fast taps","Final state correct","Positive"),
# MORE EDGE CASES
@("TC_336","Unit","Personal Info","Verify email with subdomains","Enter email with subdomain","user@mail.co.uk","Email saved","Positive"),
@("TC_337","Unit","Personal Info","Verify international phone","Enter international phone","+44 20 7946 0958","Phone saved","Positive"),
@("TC_338","Unit","Personal Info","Verify LinkedIn URL","Enter LinkedIn URL","https://linkedin.com/in/user","URL saved","Positive"),
@("TC_339","Unit","Personal Info","Verify invalid LinkedIn URL","Enter invalid URL","not-a-url","Error shown","Negative"),
@("TC_340","Unit","Personal Info","Verify GitHub URL","Enter GitHub URL","https://github.com/user","URL saved","Positive"),
@("TC_341","Unit","Work Experience","Verify job description length","Enter 1000 char description","1000 chars","Saved or truncated","Positive"),
@("TC_342","Unit","Work Experience","Verify empty job title","Leave job title empty","","Error shown","Negative"),
@("TC_343","Unit","Work Experience","Verify empty company name","Leave company name empty","","Error shown","Negative"),
@("TC_344","Unit","Work Experience","Verify future start date","Enter future start date","2030-01-01","Warning shown","Negative"),
@("TC_345","Unit","Education","Verify empty institution","Leave institution empty","","Error shown","Negative"),
@("TC_346","Unit","Education","Verify empty degree","Leave degree empty","","Error shown","Negative"),
@("TC_347","Unit","Education","Verify GPA field","Enter GPA","3.8","GPA saved","Positive"),
@("TC_348","Unit","Education","Verify invalid GPA","Enter GPA > 4.0","5.0","Error shown","Negative"),
@("TC_349","Unit","Skills","Verify max skills","Add 50 skills","50 skills","All saved or limit shown","Positive"),
@("TC_350","Unit","Skills","Verify empty skill level","Add skill without level","No level","Default level used","Positive"),
@("TC_351","Unit","Projects","Verify empty project name","Leave project name empty","","Error shown","Negative"),
@("TC_352","Unit","Projects","Verify max projects","Add 20 projects","20 projects","All saved","Positive"),
@("TC_353","Unit","Certifications","Verify empty cert name","Leave cert name empty","","Error shown","Negative"),
@("TC_354","Unit","Certifications","Verify no expiry date","Leave expiry date empty","","Entry saved","Positive"),
@("TC_355","Unit","Languages","Verify max languages","Add 15 languages","15 languages","All saved","Positive"),
@("TC_356","Integration","Export","Export with no photo","Export without profile photo","No photo","PDF without photo","Positive"),
@("TC_357","Integration","Export","Export with photo","Export with profile photo","JPEG photo","PDF with photo","Positive"),
@("TC_358","Integration","Export","Export with all skill levels","Export with Beginner/Intermediate/Expert skills","All levels","PDF shows levels","Positive"),
@("TC_359","Integration","Export","Export with multiple job entries","Export with 5 work experiences","5 entries","PDF shows all","Positive"),
@("TC_360","Integration","Export","Export with multiple degrees","Export with 3 education entries","3 entries","PDF shows all","Positive"),
@("TC_361","System","Performance","Export time with max data","Max data in all sections, measure export time","Max data","< 15 seconds","Positive"),
@("TC_362","System","Reliability","App stable after 1 hour use","Use app for 1 hour continuously","","No crash or freeze","Positive"),
@("TC_363","System","Reliability","App stable after 100 saves","Save resume 100 times","100 saves","No data corruption","Positive"),
@("TC_364","System","Reliability","App stable after 100 exports","Export 100 times","100 exports","No errors","Positive"),
@("TC_365","System","Compatibility","App works on Android 10","Test on Android 10","Android 10","App works","Positive"),
@("TC_366","System","Compatibility","App works on Android 12","Test on Android 12","Android 12","App works","Positive"),
@("TC_367","System","Compatibility","App works on iOS 15","Test on iOS 15","iOS 15","App works","Positive"),
@("TC_368","System","Compatibility","App works on iOS 17","Test on iOS 17","iOS 17","App works","Positive"),
@("TC_369","System","Compatibility","App works on Chrome browser","Test on Chrome","Chrome","App works","Positive"),
@("TC_370","System","Compatibility","App works on Safari","Test on Safari","Safari","App works","Positive"),
@("TC_371","Functional","Resume Template","Template preview shows correctly","Open template modal, check each preview","All templates","Correct previews","Positive"),
@("TC_372","Functional","Resume Template","Template selection persists","Select template, close, reopen","Classic","Template persists","Positive"),
@("TC_373","Functional","Resume Language","Language selection persists","Select language, close, reopen","French","Language persists","Positive"),
@("TC_374","Functional","Resume Language","Section labels update on language change","Change to French, check labels","French","Labels in French","Positive"),
@("TC_375","Functional","Resume Language","Placeholder text updates on language change","Change to Spanish, check placeholders","Spanish","Placeholders in Spanish","Positive"),
@("TC_376","Performance","App Launch","Cold start < 3 seconds","Kill app, reopen, measure","","< 3 seconds","Positive"),
@("TC_377","Performance","App Launch","Warm start < 1 second","Switch away and back, measure","","< 1 second","Positive"),
@("TC_378","Security","Input Validation","Unicode injection in fields","Enter Unicode in all fields","Unicode chars","Data saved safely","Positive"),
@("TC_379","Security","Input Validation","Null bytes in fields","Enter null bytes in fields","Null bytes","Input sanitized","Negative"),
@("TC_380","Security","Input Validation","Very long input in all fields","Enter 10000 chars in fields","10000 chars","App handles gracefully","Negative"),
@("TC_381","Usability","Responsiveness","UI adapts to landscape orientation","Rotate device to landscape","","UI adapts","Positive"),
@("TC_382","Usability","Responsiveness","UI adapts to portrait orientation","Rotate device to portrait","","UI adapts","Positive"),
@("TC_383","Usability","Responsiveness","UI adapts to tablet","Open on tablet","","UI adapts","Positive"),
@("TC_384","Usability","Consistency","Button styles consistent","Check all button styles","","Consistent styles","Positive"),
@("TC_385","Usability","Consistency","Card styles consistent","Check all card styles","","Consistent styles","Positive"),
@("TC_386","Regression","Notifications","All 6 toggles work after app update","Update app, test all toggles","All toggles","All work correctly","Positive"),
@("TC_387","Regression","Notifications","Toggle states persist after update","Set states, update app, check","Saved states","States persisted","Positive"),
@("TC_388","Smoke","Notifications","Notifications screen opens","Navigate to Notifications","","Screen loads","Positive"),
@("TC_389","Smoke","Notifications","At least one toggle works","Toggle Push Notifications","","Toggle changes","Positive"),
@("TC_390","Sanity","Notifications","Toggles work after bug fix","Apply fix, test all toggles","","All work","Positive"),
@("TC_391","Performance","Notifications","Notifications screen loads fast","Open Notifications, measure","","< 1 second","Positive"),
@("TC_392","Security","Notifications","Notification prefs not leaked","Check logs for notification prefs","","No PII in logs","Positive"),
@("TC_393","Usability","Notifications","Toggle labels are clear","Check toggle labels","","Labels are descriptive","Positive"),
@("TC_394","Usability","Notifications","Toggle states are visually clear","Check ON/OFF visual state","","ON/OFF clearly visible","Positive"),
@("TC_395","Usability","Notifications","Subtitles are descriptive","Check subtitles for each toggle","","Clear descriptions","Positive"),
# DATA VARIATION TESTS
@("TC_396","Functional","Personal Info","Save with minimum required data","Fill only required fields","Min data","Data saved","Positive"),
@("TC_397","Functional","Personal Info","Save with maximum data","Fill all fields with max chars","Max data","Data saved","Positive"),
@("TC_398","Functional","Personal Info","Save with Unicode name","Enter Unicode name","Ünïcödé Nàmé","Data saved","Positive"),
@("TC_399","Functional","Personal Info","Save with Arabic name","Enter Arabic name","محمد علي","Data saved","Positive"),
@("TC_400","Functional","Personal Info","Save with Chinese name","Enter Chinese name","张伟","Data saved","Positive"),
@("TC_401","Functional","Work Experience","Add entry with all fields","Fill all work exp fields","Full entry","Entry saved","Positive"),
@("TC_402","Functional","Work Experience","Add entry with minimum fields","Fill only required fields","Min entry","Entry saved","Positive"),
@("TC_403","Functional","Work Experience","Add entry with HTML in description","Enter HTML in description","<b>bold</b>","HTML sanitized","Negative"),
@("TC_404","Functional","Work Experience","Add entry with URL in description","Enter URL in description","https://example.com","URL saved","Positive"),
@("TC_405","Functional","Skills","Add skill with max length name","Enter 100 char skill name","100 chars","Saved or truncated","Positive"),
@("TC_406","Functional","Skills","Add skill with numbers","Enter numeric skill name","123","Skill saved","Positive"),
@("TC_407","Functional","Skills","Add skill with special chars","Enter special chars","!@#$%","Error or sanitized","Negative"),
@("TC_408","Functional","Projects","Add project with long description","Enter 2000 char description","2000 chars","Saved or truncated","Positive"),
@("TC_409","Functional","Projects","Add project with multiple tech tags","Add 10 technology tags","10 tags","All saved","Positive"),
@("TC_410","Functional","Projects","Add project with GitHub link","Enter GitHub link","https://github.com/project","Link saved","Positive"),
@("TC_411","Functional","Certifications","Add cert with issuer","Enter issuer name","AWS","Cert saved","Positive"),
@("TC_412","Functional","Certifications","Add cert with credential ID","Enter credential ID","AWS-123456","ID saved","Positive"),
@("TC_413","Functional","Certifications","Add cert with credential URL","Enter credential URL","https://verify.cert.com","URL saved","Positive"),
@("TC_414","Functional","Languages","Add language with Native proficiency","Select Native proficiency","Native","Saved correctly","Positive"),
@("TC_415","Functional","Languages","Add language with Fluent proficiency","Select Fluent proficiency","Fluent","Saved correctly","Positive"),
@("TC_416","Functional","Languages","Add language with Basic proficiency","Select Basic proficiency","Basic","Saved correctly","Positive"),
@("TC_417","Functional","Languages","Add language with Intermediate proficiency","Select Intermediate proficiency","Intermediate","Saved correctly","Positive"),
@("TC_418","Integration","Full Flow","Create resume, change template, export","Fill all, change to Classic, export","Classic template","PDF with Classic","Positive"),
@("TC_419","Integration","Full Flow","Create resume, change language, export","Fill all, change to French, export","French language","PDF in French","Positive"),
@("TC_420","Integration","Full Flow","Create resume with max data, export","Fill all with max data, export","Max data","PDF generated","Positive"),
@("TC_421","Integration","Full Flow","Create multiple resumes, export all","Create 3 resumes, export each","3 full resumes","3 PDFs generated","Positive"),
@("TC_422","Integration","Full Flow","Edit existing resume, export","Open saved resume, edit, export","Updated data","PDF with updated data","Positive"),
@("TC_423","Integration","Full Flow","Duplicate resume, edit, export","Duplicate, edit copy, export copy","Modified copy","PDF with copy data","Positive"),
@("TC_424","Integration","Full Flow","Share resume after export","Export, then share with contact","PDF + share","Resume shared","Positive"),
@("TC_425","System","E2E","New user creates and exports resume","New user: fill all, choose template, export","New user flow","PDF created and saved","Positive"),
@("TC_426","System","E2E","Returning user updates resume","Login, find old resume, update, re-export","Updated data","Updated PDF","Positive"),
@("TC_427","System","E2E","User changes template mid-creation","Fill 4 sections, change template, fill rest, export","Template switch mid-way","Correct PDF","Positive"),
@("TC_428","System","E2E","User switches language mid-creation","Fill 4 sections, change language, fill rest, export","Language switch","Correct PDF in new language","Positive"),
@("TC_429","System","E2E","User deletes incomplete resume","Start resume, leave incomplete, delete","","Resume deleted","Positive"),
@("TC_430","System","E2E","User restores deleted resume","Delete resume, restore","","Resume restored with data","Positive"),
@("TC_431","System","E2E","User enables all notifications","Open Notifications, enable all","All ON","All notifications active","Positive"),
@("TC_432","System","E2E","User disables all notifications","Open Notifications, disable all","All OFF","No notifications","Positive"),
@("TC_433","System","E2E","User customizes notification preferences","Enable Push, disable Email, enable others","Mixed","Correct prefs saved","Positive"),
@("TC_434","System","E2E","User exports resume with notifications on","Enable all notifications, create resume, export","Full flow","PDF generated, notifications active","Positive"),
@("TC_435","System","E2E","User changes template and language, exports","Change template to Classic and language to French, export","Classic+French","PDF in French with Classic template","Positive"),
# BOUNDARY VALUE TESTS
@("TC_436","Unit","Personal Info","Name at minimum length","Enter 1 character name","A","Saved or error","Positive"),
@("TC_437","Unit","Personal Info","Name at maximum length","Enter 100 character name","100 chars","Saved or truncated","Positive"),
@("TC_438","Unit","Personal Info","Name just above maximum","Enter 101 character name","101 chars","Error shown","Negative"),
@("TC_439","Unit","Personal Info","Email at minimum length","Enter shortest valid email","a@b.co","Email saved","Positive"),
@("TC_440","Unit","Personal Info","Phone at minimum digits","Enter 7 digit phone","1234567","Saved or error","Positive"),
@("TC_441","Unit","Work Experience","Start year minimum","Enter year 1900","1900","Year saved","Positive"),
@("TC_442","Unit","Work Experience","Start year maximum","Enter current year","2026","Year saved","Positive"),
@("TC_443","Unit","Work Experience","Start year future","Enter year 2099","2099","Warning shown","Negative"),
@("TC_444","Unit","Education","Graduation year minimum","Enter year 1900","1900","Year saved","Positive"),
@("TC_445","Unit","Education","Graduation year maximum","Enter current year","2026","Year saved","Positive"),
@("TC_446","Unit","Education","Graduation year future","Enter year 2099","2099","Year saved (future degree)","Positive"),
@("TC_447","Unit","Skills","Skill name minimum","Enter 1 char skill name","A","Saved or error","Positive"),
@("TC_448","Unit","Skills","Skill name maximum","Enter 50 char skill name","50 chars","Saved","Positive"),
@("TC_449","Unit","Skills","Skill name above maximum","Enter 51 char skill name","51 chars","Error or truncated","Negative"),
@("TC_450","Unit","Projects","Description minimum","Enter 1 char description","A","Saved","Positive"),
@("TC_451","Unit","Projects","Description maximum","Enter 500 char description","500 chars","Saved","Positive"),
@("TC_452","Unit","Projects","Description above maximum","Enter 501 char description","501 chars","Error or truncated","Negative"),
# CROSS-PLATFORM TESTS
@("TC_453","System","Cross-Platform","Resume created on Android viewable on iOS","Create on Android, view on iOS","Android resume","Correct on iOS","Positive"),
@("TC_454","System","Cross-Platform","Resume created on iOS viewable on Android","Create on iOS, view on Android","iOS resume","Correct on Android","Positive"),
@("TC_455","System","Cross-Platform","Resume created on web viewable on mobile","Create on web, view on mobile","Web resume","Correct on mobile","Positive"),
@("TC_456","System","Cross-Platform","PDF export consistent across platforms","Export on Android and iOS, compare","Same data","Identical PDFs","Positive"),
# LOCALIZATION TESTS
@("TC_457","Functional","Localization","App title in English","Set language to English, check app title","English","Title in English","Positive"),
@("TC_458","Functional","Localization","App title in French","Set language to French, check app title","French","Title in French","Positive"),
@("TC_459","Functional","Localization","App title in Spanish","Set language to Spanish, check app title","Spanish","Title in Spanish","Positive"),
@("TC_460","Functional","Localization","Date format in English","Set English, check date format","English","MM/DD/YYYY","Positive"),
@("TC_461","Functional","Localization","Date format in French","Set French, check date format","French","DD/MM/YYYY","Positive"),
@("TC_462","Functional","Localization","Currency format in Arabic","Set Arabic, check currency","Arabic","Correct format","Positive"),
@("TC_463","Functional","Localization","RTL layout in Arabic","Set Arabic, check layout direction","Arabic","RTL layout","Positive"),
@("TC_464","Functional","Localization","LTR layout in English","Set English, check layout direction","English","LTR layout","Positive"),
# ACCESSIBILITY TESTS
@("TC_465","Usability","Accessibility","All images have alt text","Check all images for alt text","","Alt text present","Positive"),
@("TC_466","Usability","Accessibility","All inputs have labels","Check all input fields for labels","","Labels present","Positive"),
@("TC_467","Usability","Accessibility","Focus order is logical","Tab through all elements","","Logical focus order","Positive"),
@("TC_468","Usability","Accessibility","Error messages announced by screen reader","Trigger error, check screen reader","","Error announced","Positive"),
@("TC_469","Usability","Accessibility","Success messages announced","Perform action, check screen reader","","Success announced","Positive"),
@("TC_470","Usability","Accessibility","Minimum touch target size","Check all tap targets","","44x44px minimum","Positive"),
@("TC_471","Usability","Accessibility","No content flashes","Check for flashing content","","No flashes > 3 per sec","Positive"),
@("TC_472","Usability","Accessibility","Zoom text to 200%","Zoom browser to 200%","200% zoom","Content still readable","Positive"),
# ERROR HANDLING TESTS
@("TC_473","Functional","Error Handling","Network error on save","Disconnect, try to save","No network","Error message shown","Negative"),
@("TC_474","Functional","Error Handling","Network error on export","Disconnect, try to export","No network","Error message shown","Negative"),
@("TC_475","Functional","Error Handling","Network error on load","Disconnect, try to load resume","No network","Error message with retry","Negative"),
@("TC_476","Functional","Error Handling","Server error handled","Simulate 500 error","500 response","Error message shown","Negative"),
@("TC_477","Functional","Error Handling","Timeout handled","Simulate slow server","Timeout","Timeout message shown","Negative"),
@("TC_478","Functional","Error Handling","Invalid data from server","Server returns bad data","Malformed JSON","Error handled gracefully","Negative"),
@("TC_479","Functional","Error Handling","App recovers after crash","Force close, reopen","","Data intact","Positive"),
@("TC_480","Functional","Error Handling","Storage error handled","Simulate storage failure","Storage error","Error message shown","Negative"),
# FINAL COMPREHENSIVE TESTS
@("TC_481","Functional","Full Resume","Create resume with all sections, all data","Fill every field in every section","Comprehensive data","All data saved","Positive"),
@("TC_482","Functional","Full Resume","Export comprehensive resume","All data filled, export","Full data","Complete PDF","Positive"),
@("TC_483","System","Full Flow","New user complete flow","Register, fill resume, export, share","New user","Resume created and shared","Positive"),
@("TC_484","System","Full Flow","Power user flow","Create 5 resumes with different templates","5 resumes","All created correctly","Positive"),
@("TC_485","Regression","Full Suite","All features work after major update","Major version update, test all","All features","Everything works","Positive"),
@("TC_486","Performance","Full Export","Large resume export < 15s","Fill all with max data, export, time","Max data","< 15 seconds","Positive"),
@("TC_487","Security","Full Security","No PII in logs or errors","Check all logs after full flow","","No PII exposed","Positive"),
@("TC_488","Usability","Full Usability","New user completes resume in 15 mins","Time new user creating first resume","New user","< 15 minutes","Positive"),
@("TC_489","Functional","Notifications","Notification screen renders all 6 toggles","Open Notifications screen","","6 toggles visible","Positive"),
@("TC_490","Functional","Notifications","Notification prefs survive app reinstall","Set prefs, reinstall app, check","Saved prefs","Prefs restored if cloud-synced","Positive"),
@("TC_491","Integration","Notifications","Notification pref change triggers actual notification update","Toggle push, verify system notif updated","","System notif setting updated","Positive"),
@("TC_492","Security","Notifications","Notification prefs encrypted in storage","Check SharedPreferences storage","","Data encrypted","Positive"),
@("TC_493","Usability","Notifications","Notification screen accessible","Enable screen reader, navigate","","All elements accessible","Positive"),
@("TC_494","Performance","Notifications","All toggle states save within 500ms","Toggle each, measure save time","","< 500ms per toggle","Positive"),
@("TC_495","Regression","All Sections","All section cards still visible after update","Update app, check section cards","","All 8 cards visible","Positive"),
@("TC_496","Regression","All Sections","All section data intact after update","Update app, check saved data","","All data intact","Positive"),
@("TC_497","Smoke","Full App","All major screens load","Navigate to every screen","","All screens load","Positive"),
@("TC_498","Smoke","Full App","No crashes on startup","Open app fresh","","No crash","Positive"),
@("TC_499","Smoke","Full App","Export works end-to-end","Full resume, export","Full data","PDF generated","Positive"),
@("TC_500","System","Full E2E","Complete hiring workflow","Create resume, export PDF, share with recruiter","Full data","Recruiter receives PDF","Positive")
)

$row = 2
foreach ($r in $rows) {
    for ($c = 1; $c -le $r.Count; $c++) {
        $sheet.Cells.Item($row, $c) = $r[$c-1]
    }
    # Color Positive rows light green, Negative rows light red
    if ($r[$r.Count-1] -eq "Positive") {
        $sheet.Rows.Item($row).Interior.ColorIndex = 35   # light green
    } else {
        $sheet.Rows.Item($row).Interior.ColorIndex = 22   # light pink/red
    }
    $row++
}

# Auto-fit columns
$usedRange = $sheet.UsedRange
$usedRange.EntireColumn.AutoFit() | Out-Null

# Add AutoFilter so user can filter by Type, Section, Positive/Negative, etc.
$sheet.Rows.Item(1).AutoFilter() | Out-Null

# Freeze header row
$excel.ActiveWindow.SplitRow = 1
$excel.ActiveWindow.FreezePanes = $true

# Save as true xlsx
$workbook.SaveAs($outputPath, 51)   # 51 = xlOpenXMLWorkbook (.xlsx)
$workbook.Close($false)
$excel.Quit()

[System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null

Write-Host "Done! File saved to: $outputPath"
