// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpKHvHo6wv9Sw3sH8CCO0mMTrinXuxgCY',
    appId: '1:42581559002:web:19611ea19f6531320947e3',
    messagingSenderId: '42581559002',
    projectId: 'resume-app-sms',
    authDomain: 'resume-app-sms.firebaseapp.com',
    storageBucket: 'resume-app-sms.firebasestorage.app',
    measurementId: 'G-Q0NQX2GS9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANuDvsv_pwMheTF7eMnNEJscYWga3vxss',
    appId: '1:42581559002:android:479c9737d18c2b080947e3',
    messagingSenderId: '42581559002',
    projectId: 'resume-app-sms',
    storageBucket: 'resume-app-sms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD51nsGAXPhRqjacoONZhwvQ0b9LqEL0KE',
    appId: '1:42581559002:ios:2ff39a5578049fcc0947e3',
    messagingSenderId: '42581559002',
    projectId: 'resume-app-sms',
    storageBucket: 'resume-app-sms.firebasestorage.app',
    iosBundleId: 'com.example.resumeBuilderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD51nsGAXPhRqjacoONZhwvQ0b9LqEL0KE',
    appId: '1:42581559002:ios:2ff39a5578049fcc0947e3',
    messagingSenderId: '42581559002',
    projectId: 'resume-app-sms',
    storageBucket: 'resume-app-sms.firebasestorage.app',
    iosBundleId: 'com.example.resumeBuilderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpKHvHo6wv9Sw3sH8CCO0mMTrinXuxgCY',
    appId: '1:42581559002:web:0135925f3f253eee0947e3',
    messagingSenderId: '42581559002',
    projectId: 'resume-app-sms',
    authDomain: 'resume-app-sms.firebaseapp.com',
    storageBucket: 'resume-app-sms.firebasestorage.app',
    measurementId: 'G-LMYM1D9DRG',
  );
}
